#include "A.h"




void A::perimetre(void  sequential)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--93-1-589e4576:16deea1dde3:-8000:0000000000000D5D begin
{
}
// section -64--88--93-1-589e4576:16deea1dde3:-8000:0000000000000D5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void A::aire(void  sequential)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--93-1-589e4576:16deea1dde3:-8000:0000000000000D60 begin
{
}
// section -64--88--93-1-589e4576:16deea1dde3:-8000:0000000000000D60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
