#include "Document.h"




void Document::ouvrir()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D90 begin
{
}
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D90 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Document::fermer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D92 begin
{
}
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D92 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
