#include "Feuillet.h"




void Feuillet::ouvrir()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D94 begin
{
}
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D94 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Feuillet::Fermer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D96 begin
{
}
// section -64--88--93-1--70f68332:16ef3e9bd5d:-8000:0000000000000D96 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
